### ISSUE TITLE
Wordpress HTML ERROR 500

### ISSUE THREAD

**Issue by vanrensav** [Screenly/Screenly-Cast-for-WordPress#6] opened 2017-06-11 19:40 UTC
Hi,

Id like to use your new plugin with love.
But after serveral tries i give up installing the plugin.

After i enable it it just crashes my wordpress.

Do you have a fix?

Here is a screenshot
![naamloos](https://user-images.githubusercontent.com/28643495/27013964-99738998-4eee-11e7-82cf-3b99a30d9093.png)

**Comment by petermonte** [comment] 2017-06-11 21:50
@vanrensav,

Can you provide more detail on what is your WP version? Also in that order, would help to understand what plugins you have installed.

In the mean time, try to disable all plugins and activate only Screenly Cast.
**If all goes ok**, start activating all plugins, on-by-one until you get the error.

If the error continues please access your plugin Screenly Cast folder via FTP and either delete it or rename it.

**Comment by vanrensav** [comment] 2017-06-12 07:00
@petermonte 

My WP version is 4.8. At this moment i dont have any plugins installed.

If i install the screenly plugin everything goes fine but when i click enable i get the 500 error.
When i delete the screenly plugin folder in ftp WP will function again.

**Comment by vpetersson** [comment] 2017-06-12 09:56
@vanrensav, just a few more questions:

 * Are you using a localized version of WordPress (i.e. non-English)
 * What type of content are you using? Is it a post, page or media page? Also, can you provide the relative URL such that we can reproduce it?

**Comment by vanrensav** [comment] 2017-06-12 10:36
Yes, its the dutch version.
I am using no content yet because i could not start using it. But i want to use the posts.

The screenly plugin was in ftp.strato.com/WordPress_10/wp-content/plugins

**Comment by vpetersson** [comment] 2017-06-12 10:37
I just spoke to @petermonte and he has a lead. A potential fix is coming soon!

**Comment by vanrensav** [comment] 2017-06-12 11:06
Okey, i wait for it.
Thanks for the fast response!

**Comment by vpetersson** [comment] 2017-06-12 11:10
@vanrensav Should be live now. Could you please try upgrading the latest version?

**Comment by vanrensav** [comment] 2017-06-12 11:16
@vpetersson still the same issue

**Comment by vpetersson** [comment] 2017-06-12 11:20
:(

Ok, what's your environment like? What webserver are you using? How is PHP configured etc?

**Comment by vanrensav** [comment] 2017-06-12 11:35
Im using strato as hosting.
I have a all in one package.

I can choose in a config panel to install wordpress at the webserver.

**Comment by vpetersson** [comment] 2017-06-12 12:35
Got it. Do you know what version of PHP you're using?

**Comment by vanrensav** [comment] 2017-06-12 12:44
PHP Version 5.3.29

**Comment by vpetersson** [comment] 2017-06-12 12:44
Also, are you able to pull down any server logs (PHP/Apache/Nginx)? We're unable to reproduce this unfortunately.

**Comment by vanrensav** [comment] 2017-06-12 12:47
I changed the php version to 11 and now it works.
Im sorry :)

**Comment by vpetersson** [comment] 2017-06-12 12:51
PHP 11? The latest version is 7.1.6. I assume you mean that. I'm still curious to know what version you were running before such that we can test and fix that.

**Comment by vanrensav** [comment] 2017-06-12 12:57
Oh yeah typo.
Its Was 5.3.29 (with issue)
Now its 7.1.3 (no issues)

**Comment by vpetersson** [comment] 2017-06-12 13:04
Got it. Thanks. I've tested with the following PHP versions:

 * 5.6
 * 7.0
 * 7.1

It works in all these versions. Will close this out as 5.3 is a pretty old version.

**Closed as completed by vpetersson** 2017-06-12 13:04 UTC
